name: prometheus-pushgateway
category: cloud
description: Prometheus Pushgateway的存在是为了允许临时作业和批处理作业将其指标公开给Prometheus。由于此类工作可能存在的时间不够长而无法被删除，因此他们可以将其指标推送到Pushgateway。然后Pushgateway将这些指标公开给Prometheus。
environment: |
  本应用以容器镜像的方式供用户使用，运行于预置docker的Linux环境。Docker的推荐安装方式如下：
  ## apt安装
  ### 1.更新系统软件包依赖
  ```
  sudo spt update
  sudo apt install ca-certificates curl gnupg lsb-release
  ```
  ### 2.添加Docker官方GPG密钥
  ```
  sudo mkdir -p /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  sudo chmod a+r /etc/apt/keyrings/docker.gpg
  ```
  ### 3.添加Docker官方APT源
  ```
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  ```
  ### 4.再次更新软件包索引
  ```
  sudo apt update
  ```
  ### 5.安装Docker
  ```
  sudo apt install docker-ce docker-ce-cli containerd.io
  ```

  ## yum安装
  ### 1.安装yum-utils
  ```
  sudo yum install -y yum-utils
  ```
  ### 2.添加Docker源
  ```
  sudo yum-config-manager \
  > --add-repo \
  > https://download.docker.com/linux/centos/docker-ce.repo
  ```
  ### 3.安装Docker
  ```
  sudo yum install -y docker-ce docker-ce-cli containerd.io
  ```

  注意，在openEuler环境安装docker时，可执行如下命令一键安装
  ```
  yum install -y docker
  ```

  ## 脚本安装
  ### 1.下载安装脚本
  ```
  curl -fsSL https://get.docker.com -o get-docker.sh
  ```
  ### 2.使用root权限执行脚本
  ```
  sudo sh get-docker.sh
  ```
  使用脚本安装方式时，如果用户要指定安装的docker版本，需要自行修改`get-docker.sh`的源码内容。

  ## 验证
  ```
  sudo docker run hello-world
  ```

download: |
  获取容器镜像
  ```
  docker pull openeuler/prometheus-pushgateway:{TAG}
  ```

install: |
  启动容器
  ```
  docker run --name prometheus-pushgateway -p 9091:9091 openeuler/prometheus-pushgateway:{TAG}
  ```
    用户可根据自身需求，自定义启动选项。

license: Apache-2.0 license
similar_packages:
  - N/A
dependency:
  - N/A