name: Alertmanager
category: cloud
description: Alertmanager处理客户端应用程序（例如Prometheus服务器）发送的警报。它负责重复数据删除、分组，并将它们路由到正确的接收器集成，例如电子邮件、PagerDuty、OpsGenie或借助Webhook接收器的许多其他机制。它还负责警报的静音和抑制。
environment: "
  本应用以容器镜像的方式供用户使用，运行于预置docker的Linux环境。Docker的推荐安装方式如下：
  ## apt安装
  ### 1.更新系统软件包依赖
  ```
  sudo spt update
  sudo apt install ca-certificates curl gnupg lsb-release
  ```
  ### 2.添加Docker官方GPG密钥
  ```
  sudo mkdir -p /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  sudo chmod a+r /etc/apt/keyrings/docker.gpg
  ```
  ### 3.添加Docker官方APT源
  ```
  echo \"deb [arch=$(dpkg --print-architecture) signed-by=/usr/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  ```
  ### 4.再次更新软件包索引
  ```
  sudo apt update
  ```
  ### 5.安装Docker
  ```
  sudo apt install docker-ce docker-ce-cli containerd.io
  ```

  ## yum安装
  ### 1.安装yum-utils
  ```
  sudo yum install -y yum-utils
  ```
  ### 2.添加Docker源
  ```
  sudo yum-config-manager \
  > --add-repo \
  > https://download.docker.com/linux/centos/docker-ce.repo
  ```
  ### 3.安装Docker
  ```
  sudo yum install -y docker-ce docker-ce-cli containerd.io
  ```

  注意，在openEuler环境安装docker时，可执行如下命令一键安装
  ```
  yum install -y docker
  ```

  ## 脚本安装
  ### 1.下载安装脚本
  ```
  curl -fsSL https://get.docker.com -o get-docker.sh
  ```
  ### 2.使用root权限执行脚本
  ```
  sudo sh get-docker.sh
  ```
  使用脚本安装方式时，如果用户要指定安装的docker版本，需要自行修改`get-docker.sh`的源码内容。

  ## 验证
  ```
  sudo docker run hello-world
  ```
  "
download: "
  获取容器镜像
  ```
  docker pull openeuler/alertmanager:{TAG}
  ```
  "
install: "
  启动容器
  ```
  docker run --name alertmanager -p 9093:9093 openeuler/alertmanager:{TAG}
  ```
    用户可根据自身需求，自定义启动选项。
  "
license: Apache-2.0 license
similar_packages:
  - VictoriaMetrics Alertmanager: 这是一个与Prometheus兼容的开源告警管理器，它提供类似于Prometheus Alertmanager的功能。它可以接收来自Prometheus的告警，并根据配置的规则进行处理和发送通知。
  - Alerta: Alerta是一个开源的事件报警工具，它可以集成各种监控系统和服务（包括Prometheus）并提供统一的事件报警和通知管理。它支持自定义规则和插件，可以根据事件的严重性和优先级进行分组和处理，还提供了丰富的通知渠道和可视化界面。
  - Grafana Alerting: Grafana是一个流行的开源数据可视化和仪表盘工具，它的最新版本中引入了Alerting功能。Grafana Alerting可以与Prometheus集成，提供类似于Alertmanager的告警管理和通知功能。它支持灵活的告警规则配置和多种通知渠道。
dependency:
  - N/A